# Generated by Django 3.0.8 on 2020-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdb',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
